version: '3.8'
services:
  postgres_database:
    container_name: database
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: omas

  spring-server:
    container_name: server
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres_database
    image: omas/webapp
