# docker-compose -f docker-compose.prod.yml up
version: '3.8'
services:
  postgres_database:
    container_name: database
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: omas
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

  spring-server:
    container_name: server
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres_database
    image: omas/webapp
    environment:
      SPRING_PROFILES_ACTIVE: prod
      OMAS_DATABASE_URL: jdbc:postgresql://postgres_database:5432/omas
      OMAS_DATABASE_USERNAME: postgres
      OMAS_DATABASE_PASSWORD: password
      OMAS_SECRET_KEY: 48794134879942idontlikedogs1323572342328789
      OMAS_SMTP_HOST: smtp.gmail.com
      OMAS_SMTP_USERNAME: 
      OMAS_SMTP_PASSWORD: 
      OMAS_SMTP_PORT: 587 
      OMAS_RECOVERY_PAGE_URL: https://localhost:3000/recovery
      OMAS_TOKEN_VALIDITY_DURATION: 28800000
      OMAS_MAX_LOGIN_ATTEMPTS: 10
      OMAS_BAN_DURATION: 86400000

